<header class="exam-header">
    <div class="d-flex align-items-center">
        <h4 class="mb-0 fw-bold text-gray-800 me-3">
            <i class="fas fa-file-alt text-primary me-2"></i> <?= $title ?>
        </h4>
        <div class="text-muted small border-start ps-3 border-2">
            Attempt ID: #<?= $attempt['id'] ?>
        </div>
    </div>

    <div class="d-flex align-items-center gap-4">
        <div class="timer-wrapper d-flex align-items-center">
            <i class="far fa-clock me-2 text-gray-500"></i>
            <div id="examTimer" class="timer-badge">00:00:00</div>
        </div>
        <button onclick="ExamEngine.confirmSubmit()" class="btn btn-primary fw-bold px-4 rounded-pill shadow-sm">
            SUBMIT EXAM
        </button>
    </div>
</header>

<div class="exam-body">
    <!-- Main Question Area -->
    <div class="question-area">
        <div class="question-card position-relative">
            <div id="questionContainer">
                <!-- Dynamic Content Loaded Here -->
                <div class="d-flex justify-content-center align-items-center h-100">
                    <div class="spinner-border text-primary" role="status"></div>
                </div>
            </div>

            <!-- Navigation Controls -->
            <div class="d-flex justify-content-between align-items-center mt-5 pt-4 border-top">
                <button onclick="ExamEngine.prev()" id="btnPrev" class="btn btn-outline-secondary px-4 rounded-pill fw-bold" disabled>
                    <i class="fas fa-arrow-left me-2"></i> Previous
                </button>
                
                <div class="form-check form-switch">
                    <input class="form-check-input" type="checkbox" id="markReview" onchange="ExamEngine.toggleReview()">
                    <label class="form-check-label fw-bold text-warning" for="markReview">Mark for Review</label>
                </div>

                <button onclick="ExamEngine.next()" id="btnNext" class="btn btn-primary px-5 rounded-pill fw-bold">
                    Next <i class="fas fa-arrow-right ms-2"></i>
                </button>
            </div>
        </div>
    </div>

    <!-- Sidebar Palette -->
    <div class="palette-sidebar">
        <h6 class="fw-bold text-gray-700 mb-3 text-uppercase small ls-1">Question Navigator</h6>
        
        <div class="d-flex gap-2 mb-4 small text-muted">
            <span class="d-flex align-items-center"><span class="w-3 h-3 bg-success rounded-circle me-1"></span> Done</span>
            <span class="d-flex align-items-center"><span class="w-3 h-3 border border-warning text-warning rounded-circle me-1 d-flex justify-content-center items-center" style="font-size:8px;">★</span> Review</span>
        </div>

        <div id="paletteGrid" class="q-grid">
            <!-- Grid generated by JS -->
        </div>

        <div class="mt-auto pt-4 text-center">
            <small class="text-muted d-block mb-1">Protected by</small>
            <strong class="text-primary"><i class="fas fa-shield-alt"></i> CivilShield™</strong>
        </div>
    </div>
</div>

<!-- Submit Modal -->
<div class="modal fade" id="submitModal" tabindex="-1">
    <div class="modal-dialog modal-dialog-centered">
        <div class="modal-content border-0 shadow-lg rounded-4">
            <div class="modal-body p-5 text-center">
                <div class="avatar avatar-xl bg-primary bg-opacity-10 text-primary rounded-circle mx-auto mb-4 d-flex align-items-center justify-content-center" style="width:80px; height:80px;">
                    <i class="fas fa-flag-checkered fa-3x"></i>
                </div>
                <h3 class="fw-bold mb-2">Ready to Submit?</h3>
                <p class="text-muted mb-4">You have answered <strong id="answeredCount">0</strong> out of <strong id="totalCount">0</strong> questions.</p>
                
                <div class="alert alert-warning border-0 rounded-3 text-start small mb-4 d-none" id="unansweredAlert">
                    <i class="fas fa-exclamation-triangle me-2"></i> Warning: You have unanswered questions.
                </div>

                <div class="d-flex gap-3 justify-content-center">
                    <button type="button" class="btn btn-light px-4 rounded-pill fw-bold" data-bs-dismiss="modal">Keep Working</button>
                    <button onclick="ExamEngine.submit()" class="btn btn-primary px-5 rounded-pill fw-bold shadow-sm">Yes, Submit</button>
                </div>
            </div>
        </div>
    </div>
</div>

<script>
    // Boot Data
    const EXAM_DATA = {
        attemptId: <?= $attempt['id'] ?>,
        durationMinutes: <?= $attempt['duration_minutes'] ?>,
        questions: <?= json_encode($questions) ?>,
        savedAnswers: <?= json_encode($savedAnswers) ?>,
        // startTime: time() // Sync server time if possible for diff
        csrf: "<?= $csrfToken ?>",
        nonce: "<?= $quizNonce ?>"
    };

    document.addEventListener('DOMContentLoaded', () => {
        ExamEngine.init(EXAM_DATA);
    });
</script>
